<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        try {
            // PostgreSQL fix: Ensure id column is auto-incrementing (BIGSERIAL/IDENTITY)
            \Illuminate\Support\Facades\DB::statement('ALTER TABLE lab_report_values ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
        } catch (\Exception $e) {
            // Already has identity or other issue - skip
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        \Illuminate\Support\Facades\DB::statement('ALTER TABLE lab_report_values ALTER COLUMN id DROP IDENTITY IF EXISTS');
    }
};
